name: deeplab-pytorch
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  # - pytorch=0.4.1
  - torchvision=0.2.1
  - h5py
  - scipy
  - matplotlib
  - pyyaml
  - click
  - tqdm
  - clang
  - clangxx
  - pydensecrf
  - pip:
    - torchnet==0.0.2
    - opencv-python==3.4.1.15
    - tensorboardX==1.2
    - tensorflow==1.9.0
    - addict